"use client";

import { applyNodeChanges, Background, Controls, MarkerType, MiniMap, ReactFlow, type Connection, type Edge, type Node, type NodeChange } from "@xyflow/react";
import "@xyflow/react/dist/style.css";
import { ArrowLeft, BookOpen, Check, GitBranch, History, Network, Pencil, Plus, RotateCcw, Save, Trash2, X } from "lucide-react";
import Link from "next/link";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { PageHead } from "@/components/ui/page-head";
import { ApiClientError, backendApi, type Concept, type LearningPathDetail, type Material, type PathEdgeType, type PathNode, type PathNodeImportance, type PathVersion } from "@/lib/api/client";

const statusLabels: Record<PathNode["status"], string> = { planned: "Запланирован", available: "Доступен", current: "Текущий", completed: "Завершён", blocked: "Заблокирован", skipped: "Пропущен" };
const edgeLabels: Record<PathEdgeType, string> = { sequence: "последовательность", prerequisite: "prerequisite", optional_branch: "optional branch", remediation: "закрытие пробела", returns_to: "возврат" };

function errorMessage(error: unknown) { return error instanceof ApiClientError ? error.message : "Не удалось изменить учебный путь"; }

export function LearningPathScreen({ spaceId, pathId }: { spaceId: string; pathId: string }) {
  const [detail, setDetail] = useState<LearningPathDetail | null>(null);
  const [concepts, setConcepts] = useState<Concept[]>([]);
  const [materials, setMaterials] = useState<Material[]>([]);
  const [versions, setVersions] = useState<PathVersion[]>([]);
  const [flowNodes, setFlowNodes] = useState<Node[]>([]);
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [editMode, setEditMode] = useState(false);
  const [dirtyLayout, setDirtyLayout] = useState(false);
  const [edgeType, setEdgeType] = useState<PathEdgeType>("sequence");
  const [modal, setModal] = useState<"node" | "resource" | "policy" | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const syncNodes = useCallback((next: LearningPathDetail) => setFlowNodes(next.nodes.map((node) => ({ id: node.id, position: { x: node.position_x ?? 0, y: node.position_y ?? 0 }, className: `path-flow-node ${node.status} ${node.importance}`, data: { label: <><small>{node.importance} · {statusLabels[node.status]}</small><strong>{node.title}</strong><span>{node.state ? `объяснение ${Math.round(node.state.explanation)}% · применение ${Math.round(node.state.application)}%` : node.node_type}</span>{node.resources.length === 0 && <em>Нет ресурсов</em>}</> } }))), []);
  const load = useCallback(async (signal?: AbortSignal) => {
    try {
      const [next, conceptItems, materialItems, versionItems] = await Promise.all([backendApi.getLearningPath(pathId, signal), backendApi.listConcepts(spaceId, signal), backendApi.listMaterials({ learningSpaceId: spaceId }, signal), backendApi.listPathVersions(pathId)]);
      setDetail(next); setConcepts(conceptItems); setMaterials(materialItems); setVersions(versionItems); syncNodes(next); setSelectedId((current) => next.nodes.some((node) => node.id === current) ? current : next.current_node?.id ?? next.nodes[0]?.id ?? null); setDirtyLayout(false); setError(null);
    } catch (requestError) { if (!signal?.aborted) setError(errorMessage(requestError)); }
    finally { if (!signal?.aborted) setLoading(false); }
  }, [pathId, spaceId, syncNodes]);
  useEffect(() => {
    const controller = new AbortController();
    void Promise.resolve().then(() => load(controller.signal));
    return () => controller.abort();
  }, [load]);

  const flowEdges = useMemo<Edge[]>(() => (detail?.edges ?? []).map((edge) => ({ id: edge.id, source: edge.source_node_id, target: edge.target_node_id, type: "smoothstep", animated: edge.edge_type === "remediation" || edge.edge_type === "returns_to", label: edgeLabels[edge.edge_type], markerEnd: { type: MarkerType.ArrowClosed }, className: `path-flow-edge ${edge.edge_type}` })), [detail?.edges]);
  const selected = detail?.nodes.find((node) => node.id === selectedId) ?? null;
  const orderedNodes = useMemo(() => [...(detail?.nodes ?? [])].sort((a, b) => (a.position_x ?? 0) - (b.position_x ?? 0) || (a.position_y ?? 0) - (b.position_y ?? 0)), [detail?.nodes]);
  function onNodesChange(changes: NodeChange[]) { setFlowNodes((nodes) => applyNodeChanges(changes, nodes)); if (changes.some((change) => change.type === "position")) setDirtyLayout(true); }
  async function connect(connection: Connection) { if (!detail || !connection.source || !connection.target) return; try { const result = await backendApi.addPathEdge(pathId, { expected_version: detail.path.version, source_node_id: connection.source, target_node_id: connection.target, edge_type: edgeType }); setDetail((current) => current ? { ...current, path: { ...current.path, version: result.path_version }, edges: [...current.edges, result.edge] } : current); } catch (requestError) { setError(errorMessage(requestError)); } }
  async function saveLayout() { if (!detail) return; let version = detail.path.version; try { for (const flowNode of flowNodes) { const original = detail.nodes.find((node) => node.id === flowNode.id); if (original && (original.position_x !== flowNode.position.x || original.position_y !== flowNode.position.y)) { const result = await backendApi.updatePathNode(pathId, flowNode.id, { expected_version: version, position_x: flowNode.position.x, position_y: flowNode.position.y }); version = result.path_version; } } await load(); } catch (requestError) { setError(errorMessage(requestError)); } }
  async function publish() { if (!detail) return; try { setDetail(await backendApi.publishLearningPath(pathId, detail.path.version)); await load(); } catch (requestError) { setError(errorMessage(requestError)); } }
  async function removeNode(node: PathNode) { if (!detail || !window.confirm(`Удалить «${node.title}»? Будут удалены ${node.resources.length} ресурсов и связанные edges.`)) return; try { await backendApi.deletePathNode(pathId, node.id, detail.path.version); await load(); } catch (requestError) { setError(errorMessage(requestError)); } }
  async function updateResource(resourceId: string, status: "completed" | "skipped") { if (!detail) return; try { await backendApi.updatePathResource(pathId, resourceId, { expected_version: detail.path.version, completion_status: status }); await load(); } catch (requestError) { setError(errorMessage(requestError)); } }
  async function completeNode(node: PathNode) { if (!detail) return; try { setDetail(await backendApi.completePathNode(pathId, node.id, detail.path.version)); await load(); } catch (requestError) { setError(requestError instanceof ApiClientError && requestError.code === "node_completion_policy_not_met" ? `Критерии не выполнены: ${String(requestError.details.blockers ?? requestError.message)}` : errorMessage(requestError)); } }
  async function skipNode(node: PathNode) { if (!detail) return; try { setDetail(await backendApi.skipPathNode(pathId, node.id, detail.path.version)); await load(); } catch (requestError) { setError(errorMessage(requestError)); } }
  async function resolveSuggestion(id: string, accept: boolean) { if (!detail) return; try { if (accept) setDetail(await backendApi.acceptPathSuggestion(id, detail.path.version)); else await backendApi.rejectPathSuggestion(id, detail.path.version); await load(); } catch (requestError) { setError(errorMessage(requestError)); } }
  async function restore(version: number) { if (!detail || !window.confirm(`Восстановить структуру версии ${version}? Текущее состояние сохранится новой версией.`)) return; try { setDetail(await backendApi.restorePathVersion(pathId, version, detail.path.version)); await load(); } catch (requestError) { setError(errorMessage(requestError)); } }

  if (loading) return <section className="card state-card"><span className="state-loader" /><h2>Собираем учебный путь…</h2></section>;
  if (!detail) return <section className="card state-card"><h2>Путь недоступен</h2><p>{error}</p></section>;
  return <>
    <Link className="back-link" href={`/spaces/${spaceId}`}><ArrowLeft /> К пространству</Link>
    <PageHead eyebrow={`${detail.path.status} · version ${detail.path.version} · ${detail.progress.percent}%`} title={detail.path.title} action={<div className="head-actions">{detail.path.status === "draft" && <button className="primary" onClick={() => void publish()} type="button">Опубликовать</button>}<button className={editMode ? "primary" : "secondary"} onClick={() => setEditMode((value) => !value)} type="button"><Pencil /> {editMode ? "Завершить edit" : "Edit mode"}</button></div>} />
    <section className="goal-banner"><span className="round-icon blue"><Network /></span><div><span>Learning Goal</span><strong>{detail.goal.title}</strong></div><div className="path-progress"><b>{detail.progress.required_completed}/{detail.progress.required_total}</b><small>required nodes</small></div></section>
    {error && <p className="inline-error">{error}</p>}
    {editMode && <section className="path-edit-toolbar card"><button className="secondary" onClick={() => setModal("node")} type="button"><Plus /> Узел</button><button className="secondary" disabled={!selected} onClick={() => setModal("resource")} type="button"><BookOpen /> Ресурс</button><button className="secondary" disabled={!selected} onClick={() => setModal("policy")} type="button"><Check /> Criteria</button><label>Новая связь<select value={edgeType} onChange={(event) => setEdgeType(event.target.value as PathEdgeType)}>{Object.entries(edgeLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><button className="secondary" disabled={!dirtyLayout} onClick={() => { syncNodes(detail); setDirtyLayout(false); }} type="button"><RotateCcw /> Undo layout</button><button className="primary" disabled={!dirtyLayout} onClick={() => void saveLayout()} type="button"><Save /> Save layout</button></section>}
    <div className="learning-path-layout">
      <section className="card path-canvas"><ReactFlow nodes={flowNodes} edges={flowEdges} onNodesChange={onNodesChange} onConnect={(connection) => void connect(connection)} onNodeClick={(_, node) => setSelectedId(node.id)} nodesDraggable={editMode} nodesConnectable={editMode} fitView fitViewOptions={{ padding: 0.25 }}><Background /><Controls /><MiniMap pannable zoomable /></ReactFlow></section>
      <aside className="card path-node-panel">{selected ? <NodePanel node={selected} editMode={editMode} onAttach={() => setModal("resource")} onPolicy={() => setModal("policy")} onRemove={() => void removeNode(selected)} onResourceStatus={updateResource} onComplete={() => void completeNode(selected)} onSkip={() => void skipNode(selected)} /> : <p>Выбери узел.</p>}</aside>
    </div>
    <section className="path-outline"><div className="section-heading"><div><p className="accent-label">Тот же граф, линейно</p><h2>Outline</h2></div></div>{orderedNodes.map((node, index) => <article className={`card path-outline-node ${node.status}`} key={node.id} onClick={() => setSelectedId(node.id)}><span className="outline-index">{index + 1}</span><div><small>{node.importance} · {statusLabels[node.status]} · {node.estimated_minutes ?? "—"} мин</small><h3>{node.title}</h3><p>{String(node.metadata.planner_rationale ?? node.metadata.draft_rationale ?? "Добавлено пользователем.")}</p><div className="outline-resources">{node.resources.map((resource) => <span key={resource.id}>{resource.resource_type}: {resource.title} · {resource.completion_status}</span>)}{node.resources.length === 0 && <span className="warning">Нет прикреплённых ресурсов</span>}</div></div></article>)}</section>
    <section className="path-bottom-grid"><div className="card suggestions-panel"><h2><GitBranch /> Предложения системы</h2>{detail.pending_suggestions.length === 0 ? <p className="muted">Нет ожидающих предложений. Система не меняет путь скрытно.</p> : detail.pending_suggestions.map((suggestion) => <article key={suggestion.id}><b>{suggestion.suggestion_type}</b><p>{suggestion.rationale}</p><details><summary>Preview changes</summary><pre>{JSON.stringify(suggestion.payload, null, 2)}</pre></details><div className="head-actions"><button className="primary" onClick={() => void resolveSuggestion(suggestion.id, true)} type="button">Accept</button><button className="secondary" onClick={() => void resolveSuggestion(suggestion.id, false)} type="button">Reject</button></div></article>)}</div><div className="card version-panel"><h2><History /> История версий</h2>{versions.map((version) => <article key={version.id}><div><b>v{version.version}</b><time>{new Date(version.created_at).toLocaleString("ru-RU")}</time></div><p>{version.change_summary}</p><button className="secondary" onClick={() => void restore(version.version)} type="button">Восстановить</button></article>)}</div></section>
    {modal === "node" && <NodeModal detail={detail} concepts={concepts} onClose={() => setModal(null)} onSaved={() => { setModal(null); void load(); }} />}
    {modal === "resource" && selected && <ResourceModal detail={detail} node={selected} materials={materials} onClose={() => setModal(null)} onSaved={(version) => { setModal(null); setDetail((current) => current ? { ...current, path: { ...current.path, version } } : current); void load(); }} />}
    {modal === "policy" && selected && <PolicyModal detail={detail} node={selected} onClose={() => setModal(null)} onSaved={() => { setModal(null); void load(); }} />}
  </>;
}

function NodePanel({ node, editMode, onAttach, onPolicy, onRemove, onResourceStatus, onComplete, onSkip }: { node: PathNode; editMode: boolean; onAttach: () => void; onPolicy: () => void; onRemove: () => void; onResourceStatus: (id: string, status: "completed" | "skipped") => Promise<void>; onComplete: () => void; onSkip: () => void }) {
  return <><span className={`status-pill ${node.status}`}>{statusLabels[node.status]}</span><h2>{node.title}</h2><p>{node.description ?? String(node.metadata.planner_rationale ?? "Контекст пути для концепции.")}</p>{node.state && <div className="node-state-grid"><span>Объяснение <b>{Math.round(node.state.explanation)}%</b></span><span>Применение <b>{Math.round(node.state.application)}%</b></span><span>Устойчивость <b>{Math.round(node.state.stability)}%</b></span><span>Confidence <b>{Math.round(node.state.confidence * 100)}%</b></span></div>}<h3>Ресурсы</h3><div className="path-resource-list">{node.resources.map((resource) => <article key={resource.id}><div><small>{resource.resource_type}{resource.is_required ? " · required" : ""}</small><b>{resource.title}</b></div><span>{resource.completion_status}</span>{resource.completion_status === "planned" && <button onClick={() => void onResourceStatus(resource.id, "completed")} type="button"><Check /> Готово</button>}</article>)}{node.resources.length === 0 && <p className="warning">Материалы не найдены: planner ничего не выдумывает.</p>}</div><h3>Completion criteria</h3>{Object.keys(node.completion_policy).length === 0 ? <p>Явное подтверждение пользователя.</p> : <pre className="policy-preview">{JSON.stringify(node.completion_policy, null, 2)}</pre>}{node.completion_blockers.length > 0 && <ul>{node.completion_blockers.map((item) => <li key={item}>{item}</li>)}</ul>}<div className="node-actions"><button className="primary" disabled={node.status === "completed"} onClick={onComplete} type="button"><Check /> Завершить узел</button>{node.importance !== "required" && <button className="secondary" onClick={onSkip} type="button">Пропустить</button>}</div>{editMode && <div className="node-actions"><button className="secondary" onClick={onAttach} type="button"><Plus /> Ресурс</button><button className="secondary" onClick={onPolicy} type="button">Criteria</button><button className="danger-button" onClick={onRemove} type="button"><Trash2 /> Удалить</button></div>}</>;
}

function NodeModal({ detail, concepts, onClose, onSaved }: { detail: LearningPathDetail; concepts: Concept[]; onClose: () => void; onSaved: () => void }) {
  const unused = concepts.filter((concept) => !detail.nodes.some((node) => node.concept_id === concept.id)); const [conceptId, setConceptId] = useState(unused[0]?.id ?? ""); const [newTitle, setNewTitle] = useState(""); const [importance, setImportance] = useState<PathNodeImportance>("required"); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null);
  async function submit(event: FormEvent) { event.preventDefault(); setSaving(true); try { let concept = concepts.find((item) => item.id === conceptId); if (!concept && newTitle) concept = await backendApi.createConcept({ learning_space_id: detail.path.learning_space_id, title: newTitle, description: null, aliases: [] }); if (!concept) throw new Error("Concept required"); await backendApi.addPathNode(detail.path.id, { expected_version: detail.path.version, concept_id: concept.id, node_type: "concept", title: concept.title, importance, position_x: detail.nodes.length * 260, position_y: 0, completion_policy: {} }); onSaved(); } catch (requestError) { setError(errorMessage(requestError)); setSaving(false); } }
  return <div className="modal-wrap" onClick={onClose}><form className="review-modal entity-form" onClick={(event) => event.stopPropagation()} onSubmit={submit}><button className="close icon-button" onClick={onClose} type="button"><X /></button><p className="accent-label">Новый узел пути</p><h2>Добавить концепцию</h2><label>Существующая<select value={conceptId} onChange={(event) => setConceptId(event.target.value)}><option value="">Создать новую</option>{unused.map((concept) => <option key={concept.id} value={concept.id}>{concept.title}</option>)}</select></label>{!conceptId && <label>Название новой концепции<input required value={newTitle} onChange={(event) => setNewTitle(event.target.value)} /></label>}<label>Важность<select value={importance} onChange={(event) => setImportance(event.target.value as PathNodeImportance)}><option value="required">required</option><option value="recommended">recommended</option><option value="optional">optional</option></select></label>{error && <p className="form-error">{error}</p>}<div className="modal-actions"><button className="secondary" onClick={onClose} type="button">Отмена</button><button className="primary" disabled={saving} type="submit">Добавить</button></div></form></div>;
}

function ResourceModal({ detail, node, materials, onClose, onSaved }: { detail: LearningPathDetail; node: PathNode; materials: Material[]; onClose: () => void; onSaved: (version: number) => void }) {
  const [type, setType] = useState<"material" | "practice" | "explanation" | "project_task">("material"); const [materialId, setMaterialId] = useState(materials[0]?.id ?? ""); const [title, setTitle] = useState(""); const [required, setRequired] = useState(true); const [error, setError] = useState<string | null>(null);
  async function submit(event: FormEvent) { event.preventDefault(); const material = materials.find((item) => item.id === materialId); try { const result = await backendApi.addPathResource(detail.path.id, node.id, { expected_version: detail.path.version, resource_type: type, resource_id: type === "material" ? materialId : null, title: type === "material" ? material?.title ?? "Материал" : title, is_required: required, order_index: node.resources.length }); onSaved(result.path_version); } catch (requestError) { setError(errorMessage(requestError)); } }
  return <div className="modal-wrap" onClick={onClose}><form className="review-modal entity-form" onClick={(event) => event.stopPropagation()} onSubmit={submit}><button className="close icon-button" onClick={onClose} type="button"><X /></button><p className="accent-label">Ресурс узла</p><h2>{node.title}</h2><label>Тип<select value={type} onChange={(event) => setType(event.target.value as typeof type)}><option value="material">Материал</option><option value="practice">Практика</option><option value="explanation">Объяснение</option><option value="project_task">Задача проекта</option></select></label>{type === "material" ? <label>Материал<select value={materialId} onChange={(event) => setMaterialId(event.target.value)}>{materials.map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</select></label> : <label>Название<input required value={title} onChange={(event) => setTitle(event.target.value)} /></label>}<label className="check-label"><input type="checkbox" checked={required} onChange={(event) => setRequired(event.target.checked)} />Обязательный ресурс</label>{error && <p className="form-error">{error}</p>}<div className="modal-actions"><button className="secondary" onClick={onClose} type="button">Отмена</button><button className="primary" disabled={type === "material" && !materialId} type="submit">Прикрепить</button></div></form></div>;
}

function PolicyModal({ detail, node, onClose, onSaved }: { detail: LearningPathDetail; node: PathNode; onClose: () => void; onSaved: () => void }) {
  const [explanation, setExplanation] = useState(60); const [materialRequired, setMaterialRequired] = useState(false); const [application, setApplication] = useState(50); const [error, setError] = useState<string | null>(null);
  async function submit(event: FormEvent) { event.preventDefault(); const all: Record<string, unknown>[] = [{ dimension: "explanation", minimum_score: explanation }]; if (materialRequired) all.unshift({ resource_type: "material", minimum_completed: 1 }); try { await backendApi.updatePathNode(detail.path.id, node.id, { expected_version: detail.path.version, completion_policy: { all, any: [{ dimension: "application", minimum_score: application }, { evidence_type: "task_solved", minimum_count: 1 }] } }); onSaved(); } catch (requestError) { setError(errorMessage(requestError)); } }
  return <div className="modal-wrap" onClick={onClose}><form className="review-modal entity-form" onClick={(event) => event.stopPropagation()} onSubmit={submit}><button className="close icon-button" onClick={onClose} type="button"><X /></button><p className="accent-label">Поддерживаемый MVP subset</p><h2>Критерии завершения</h2><label>Explanation minimum<input type="number" min="0" max="100" value={explanation} onChange={(event) => setExplanation(Number(event.target.value))} /></label><label>Application minimum в блоке any<input type="number" min="0" max="100" value={application} onChange={(event) => setApplication(Number(event.target.value))} /></label><label className="check-label"><input type="checkbox" checked={materialRequired} onChange={(event) => setMaterialRequired(event.target.checked)} />Требовать один завершённый material</label>{error && <p className="form-error">{error}</p>}<div className="modal-actions"><button className="secondary" onClick={onClose} type="button">Отмена</button><button className="primary" type="submit">Сохранить policy</button></div></form></div>;
}
